### ISSUE TITLE
Unit tests failing on OSX

### ISSUE THREAD

**Issue by ghuntley** [cake-contrib/Cake.Plist#2] opened 2016-06-28 02:20 UTC
![screen shot 2016-06-28 at 12 19 59 pm](https://cloud.githubusercontent.com/assets/127353/16401803/bab2eb84-3d2a-11e6-94a5-853ac7d2eff3.png)

**Comment by reicheltp** [comment] 2016-07-05 10:25
This was a problem caused by XUnit on Mono with InlineData. Instead of a typed array it passed an `object[]` in the test method.

Fixed on develop with 92878fabfd33574fc1d811e5bd9001575e2c83f1

**Closed as completed by reicheltp** 2016-07-05 10:25 UTC
